apiVersion: v1
kind: Pod
metadata:
  name: redis1
  namespace: default
spec:
  containers:
    - name: redis
      image: redis
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
      envFrom:
        - configMapRef: 
            name: myconfig

