apiVersion: v1
kind: Service
metadata: 
  name: http-service
  namespace: default
spec: 
  selector:
      app: myweb
  type: NodePort
  ports:
    - name: myweb
      port: 80
      targetPort: 80


