apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpv
spec:
  storageClassName: local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/mypv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - dev
