apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
spec:
  storageClassName: local
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
