apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
      volumeMounts:
        - name: localpv
          mountPath: /opt
  nodeSelector:
    env: dev
  volumes:
    - name: localpv
      persistentVolumeClaim: 
        claimName: mypvc
