apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: localpv
          mountPath: /opt
  nodeSelector:
    env: dev
  volumes:
    - name: localpv
      persistentVolumeClaim: 
        claimName: mypvc
