apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
