apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
  labels:
    app: mypod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
    ports:
    - containerPort:  80
      name:  http