apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  namespace: default
  labels:
    app: myweb
spec:
  containers:
    - name: myweb
      image: nginx:latest
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumeMounts:
         - name: local
           mountPath: /var/log//nginx
  volumes:
    - name: local
      emptyDir: {}
    - name: redis-volume