apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  namespace: default
  labels:
    app: myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata: 
      name: myreplicaset
      labels:
        app: myweb
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:             
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: local
              mountPath: /var/log/nginx
      volumes:
        - name: local
          emptyDir: {}

